### ISSUE TITLE
Apache FTPServer adapt to Apache MINA 2.2.x

### ISSUE THREAD

**Issue by 07070529** [apache/mina-ftpserver#25]
Hi, I see that Apache MINA 2.2.x rewrites the SSL/TLS layer to address some flaws that were hard to fix in 2.1.x.
Apache FTPServer depends on Apache MINA, but the latest released version of Apache FTPServer (1.2.0) still depends on Apache MINA 2.1.6.
So, I'd like to ask if there are plans to release a new version of Apache FTPServer to adapt to Apache MINA 2.2.x.

![image](https://user-images.githubusercontent.com/42636191/232437534-a7b04520-b0f1-4084-82df-d933926891aa.png)

**Comment by 07070529** [comment]
The motivation I raise this issue is that we are using Apache MINA and Apache FTP Server together. 
Currently, we are using Apache FTP Server version 1.1.3, and we want to use the more secure Apache MINA version 2.2.1. However, Apache MINA 2.2 and 2.1 have incompatible changes (https://mina.apache.org/mina-project/2.2-vs-2.1.html) . 
Using Apache FTPServer 1.1.3 with Apache MINA 2.2.1 has compatibility issues.
Therefore, we wanted to know if there are plans to release a new version of Apache FTPServer to adapt to Apache MINA 2.2.x?

**Comment by elecharny** [comment]
Hi,
that is certainly something to be done...

If you want to give it a try...

**Comment by 07070529** [comment]
Thank you for your reply and suggestions.
I'd like to contribute to the open source community, but I'm just starting to learn Java.
So, sorry, maybe I'm not able to support this work in the short term.

**Comment by elecharny** [comment]
I understand :-)

OTOH, it can be funny and a good learning experience for someone starting to learn Java! And remember we all were beginners at some point in the past, so one shoulmd not feel ashamed or scared to do mistakes. We all do a LOT even after 2 decades of Java !

**Comment by 07070529** [comment]
Thank you for your encouragement.

**Comment by elecharny** [comment]
FTR, currently working on migrating to Mina 2.2.2

**Comment by 07070529** [comment]
Wow, that's great. Thank you.

**Comment by elecharny** [comment]
Almost done, but there is a problem:

We use the getAuthValue() method as a parameter for the AUTH command and as a parameter for the sslConfigFactory.setSslProtocol() method. This is broken, as the AUTH command only accept SSL and TLS, while we may inject TLSv1.2 or TLSv1.3 in the second method.

We need to define a way to call setEnabledProtocols() method that does not use the getAuthValue() method.

Currently working on it.

**Comment by 07070529** [comment]
Looking forward to it，and sorry for not being able to offer any advice at this time.

**Comment by rohit-100** [comment]
@elecharny  i am also facing compatablity issue of mina-core-2.2.1 with ftp server. Can you pls do it soon , i am waiting for it.🙏🙏

**Comment by MikeRocke** [comment]
Heya @elecharny 
I've raised https://github.com/apache/mina-ftpserver/pull/37
Not sure if its correct, but I'd love some feedback :) 

Many thanks!!

**Comment by elecharny** [comment]
@MikeRocke  Will have a look today. Thanks!

**Comment by elecharny** [comment]
Branch 1.2.X now builds with MINA 2.2.4

**Comment by MikeRocke** [comment]
Great news! Thank you!

**Comment by 07070529** [comment]
Agreed. That's good news. Thank you very much.

**Comment by garydgregory** [comment]
I'm looking forward to a new release so I can migrate Apache Commons VFS from all old versions of Mina components! 👍

**Comment by elecharny** [comment]
I'm pretty much done with the cleaning I started. Probably time to get the release cut then :-)

Although I still have 25 javadoc errors I get to fix...

**Comment by garydgregory** [comment]
👍 🚀

**Comment by elecharny** [comment]
I'll take some extra time to fix the few tens of javadoc warnings (most of them are now gone, except for the core module).

I would also like to review [PR 55](https://github.com/apache/mina-ftpserver/pull/55/commits), which might be a good inclusion.

**Comment by MikeRocke** [comment]
Yeah, I like that in memory file idea. 

Thanks for your work @elecharny and the team :)
