### ISSUE TITLE
The schema locations are not valid anymore

### ISSUE THREAD

**Issue by lingyanmeng** [apache/mina-ftpserver#4]
The schema locations in ftpd-typical.xml are not valid anymore, shall we include them in the project:
http://mina.apache.org/ftpserver/spring/v1 http://mina.apache.org/ftpserver/ftpserver-1.0.xsd

curl -vL http://mina.apache.org/ftpserver/ftpserver-1.0.xsd
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL was not found on this server.</p>
</body></html>
* Curl_http_done: called premature == 0
* Connection #1 to host (nil) left intact

**Comment by elecharny** [comment]
I changed the location of the file which is now on https://mina.apache.org/ftpserver-project/ftpserver-1.0.xsd, and updated the ftpd-typical.xml file
