### ISSUE TITLE
why use space and tab in same line...?

### ISSUE THREAD

**Issue by XenoAmess** [apache/mina-ftpserver#6]
maybe, just maybe, you should apply some checkstyle plugin?

**Comment by elecharny** [comment]
This is just historical. Many persons have worked on the code, and some didn't have a proper formater.

I just replaced all the tabs by spaces in all the files.

**Comment by XenoAmess** [comment]
@elecharny so is it worthy to add a checkstyle plugin to this repo build chain?

**Comment by elecharny** [comment]
Sure !
